/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const IconEmojioneDesktopComputer: typeof import('~icons/emojione/desktop-computer')['default']
  const IconIcBaselineWhatsapp: typeof import('~icons/ic/baseline-whatsapp')['default']
  const IconIconParkOutlineDuck: typeof import('~icons/icon-park-outline/duck')['default']
  const IconJamComputerF: typeof import('~icons/jam/computer-f')['default']
  const IconLucideBird: typeof import('~icons/lucide/bird')['default']
  const IconMaterialSymbolsAndroid: typeof import('~icons/material-symbols/android')['default']
  const IconMaterialSymbolsBattery1Bar: typeof import('~icons/material-symbols/battery1-bar')['default']
  const IconMaterialSymbolsBrightness6OutlineRounded: typeof import('~icons/material-symbols/brightness6-outline-rounded')['default']
  const IconMaterialSymbolsCall: typeof import('~icons/material-symbols/call')['default']
  const IconMaterialSymbolsChatError: typeof import('~icons/material-symbols/chat-error')['default']
  const IconMaterialSymbolsFavorite: typeof import('~icons/material-symbols/favorite')['default']
  const IconMaterialSymbolsFitbitCheckSmall: typeof import('~icons/material-symbols/fitbit-check-small')['default']
  const IconMaterialSymbolsGalleryThumbnail: typeof import('~icons/material-symbols/gallery-thumbnail')['default']
  const IconMaterialSymbolsHomeRounded: typeof import('~icons/material-symbols/home-rounded')['default']
  const IconMaterialSymbolsInfo: typeof import('~icons/material-symbols/info')['default']
  const IconMaterialSymbolsLightSettingsRounded: typeof import('~icons/material-symbols-light/settings-rounded')['default']
  const IconMaterialSymbolsWorkspacePremiumRounded: typeof import('~icons/material-symbols/workspace-premium-rounded')['default']
  const IconMdiPiggyBankOutline: typeof import('~icons/mdi/piggy-bank-outline')['default']
  const IconMdiTurtle: typeof import('~icons/mdi/turtle')['default']
  const IconMingcuteToyHorseLine: typeof import('~icons/mingcute/toy-horse-line')['default']
  const IconPhCpuBold: typeof import('~icons/ph/cpu-bold')['default']
  const IconPhHandHeartFill: typeof import('~icons/ph/hand-heart-fill')['default']
  const IconRiComputerFill: typeof import('~icons/ri/computer-fill')['default']
  const IconTdesignSystemCode: typeof import('~icons/tdesign/system-code')['default']
}
