/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const IconMaterialSymbolsFitbitCheckSmall: typeof import('~icons/material-symbols/fitbit-check-small')['default']
  const IconMaterialSymbolsWorkspacePremiumRounded: typeof import('~icons/material-symbols/workspace-premium-rounded')['default']
}
