/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./src/App.vue')['default']
    CardView: typeof import('./src/components/serviciosView.vue')['default']
    CarouselView: typeof import('./src/components/carouselView.vue')['default']
    EleccionView: typeof import('./src/components/eleccionView.vue')['default']
    ExserviciosView: typeof import('./src/components/exserviciosView.vue')['default']
    Footer: typeof import('./src/components/footerView.vue')['default']
    FooterView: typeof import('./src/components/footerView.vue')['default']
    FormView: typeof import('./src/components/formView.vue')['default']
    GoogleMapLoader: typeof import('./src/components/googleMapLoader.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Horario: typeof import('./src/components/horarioView.vue')['default']
    HorarioView: typeof import('./src/components/horarioView.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    IIcBaselineAlarm: typeof import('~icons/ic/baseline-alarm')['default']
    IIcBaselineMiscellaneousServices: typeof import('~icons/ic/baseline-miscellaneous-services')['default']
    IIconParkOutlineDownloadComputer: typeof import('~icons/icon-park-outline/download-computer')['default']
    IIcTwotoneInstallDesktop: typeof import('~icons/ic/twotone-install-desktop')['default']
    IMaterialSymbolsApprovalDelegation: typeof import('~icons/material-symbols/approval-delegation')['default']
    IMaterialSymbolsBrightness6OutlineRounded: typeof import('~icons/material-symbols/brightness6-outline-rounded')['default']
    IMaterialSymbolsCall: typeof import('~icons/material-symbols/call')['default']
    IMaterialSymbolsCheckSmall: typeof import('~icons/material-symbols/check-small')['default']
    IMaterialSymbolsLightLocationOnOutline: typeof import('~icons/material-symbols-light/location-on-outline')['default']
    IMdiDotsVertical: typeof import('~icons/mdi/dots-vertical')['default']
    IMdiGmail: typeof import('~icons/mdi/gmail')['default']
    IntroView: typeof import('./src/components/introView.vue')['default']
    IPhDesktopTowerDuotone: typeof import('~icons/ph/desktop-tower-duotone')['default']
    IPhDesktopTowerFill: typeof import('~icons/ph/desktop-tower-fill')['default']
    IPhEnvelopeLight: typeof import('~icons/ph/envelope-light')['default']
    IRiWhatsappFill: typeof import('~icons/ri/whatsapp-fill')['default']
    MisionView: typeof import('./src/components/misionView.vue')['default']
    Nav: typeof import('./src/components/Nav.vue')['default']
    NavView: typeof import('./src/components/NavView.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCarousel: typeof import('naive-ui')['NCarousel']
    Planes: typeof import('./src/hooks/Planes.vue')['default']
    PlanesView: typeof import('./src/components/planesView.vue')['default']
    Principal: typeof import('./src/hooks/Principal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiciosView: typeof import('./src/components/serviciosView.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
