/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./src/App.vue')['default']
    CarouselView: typeof import('./src/components/carouselView.vue')['default']
    EleccionView: typeof import('./src/components/choice/eleccionView.vue')['default']
    FooterView: typeof import('./src/components/footerView.vue')['default']
    FormView: typeof import('./src/components/smallForm/formView.vue')['default']
    GoogleMapLoader: typeof import('./src/components/location/googleMapLoader.vue')['default']
    HorarioView: typeof import('./src/components/location/horarioView.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    IIcBaselineWhatsapp: typeof import('~icons/ic/baseline-whatsapp')['default']
    IMaterialSymbolsLightLocationOnOutline: typeof import('~icons/material-symbols-light/location-on-outline')['default']
    IMaterialSymbolsLightPerson: typeof import('~icons/material-symbols-light/person')['default']
    IMdiDotsVertical: typeof import('~icons/mdi/dots-vertical')['default']
    IMdiGmail: typeof import('~icons/mdi/gmail')['default']
    IntroView: typeof import('./src/components/introView.vue')['default']
    IPhEnvelopeLight: typeof import('~icons/ph/envelope-light')['default']
    IRiWhatsappFill: typeof import('~icons/ri/whatsapp-fill')['default']
    Listatickets: typeof import('./src/components/modules/tickets/listatickets.vue')['default']
    Login: typeof import('./src/components/login/login.vue')['default']
    Modal: typeof import('./src/components/modules/form/modal.vue')['default']
    Navbar: typeof import('./src/components/layout/menu/navbar.vue')['default']
    NavView: typeof import('./src/components/NavView.vue')['default']
    NCarousel: typeof import('naive-ui')['NCarousel']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NewTicket: typeof import('./src/components/modules/tickets/newTicket.vue')['default']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    OtraeleccionView: typeof import('./src/components/otraeleccionView.vue')['default']
    Panel: typeof import('./src/components/layout/panel/panel.vue')['default']
    PlanesView: typeof import('./src/components/plans/planesView.vue')['default']
    PlanView: typeof import('./src/components/plans/planView.vue')['default']
    Principal: typeof import('./src/hooks/Principal.vue')['default']
    Principalhp: typeof import('./src/hooks/principalhp.vue')['default']
    Prueba: typeof import('./src/components/modules/form/prueba.vue')['default']
    Prueba2: typeof import('./src/components/modules/tickets/prueba2.vue')['default']
    PruebaView: typeof import('./src/components/pruebaView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiciosView: typeof import('./src/components/serviciosView.vue')['default']
    Sidebar: typeof import('./src/components/layout/menu/sidebar.vue')['default']
    SistemasView: typeof import('./src/components/sistemasView.vue')['default']
    TextForm: typeof import('./src/components/smallForm/textForm.vue')['default']
  }
}
